In [20]:
from numpy import *
from numpy import diag
from numpy import dot
from numpy import linalg
import math

a = array([[0,1,1],[math.sqrt(2),2,0],[0,1,1]])


In [21]:
def svd(matrix):
    U, s, V = linalg.svd(a)
    print(U)
    print(s)
    print(V)
    print("/////////////////////////////")
    Sigma = diag(s)
    B = V.dot(Sigma.dot(V))
    print(U)
    print(B)
    print(V)


In [22]:
svd(a)

[[-0.40824829  0.57735027 -0.70710678]
 [-0.81649658 -0.57735027  0.        ]
 [-0.40824829  0.57735027  0.70710678]]
[ 2.82842712  1.41421356 -0.        ]
[[ -4.08248290e-01  -8.66025404e-01  -2.88675135e-01]
 [ -5.77350269e-01  -5.55111512e-17   8.16496581e-01]
 [ -7.07106781e-01   5.00000000e-01  -5.00000000e-01]]
/////////////////////////////
[[-0.40824829  0.57735027 -0.70710678]
 [-0.81649658 -0.57735027  0.        ]
 [-0.40824829  0.57735027  0.70710678]]
[[ 1.1785113   1.         -0.66666667]
 [ 0.66666667  1.41421356  0.47140452]
 [ 0.40824829  1.73205081  1.15470054]]
[[ -4.08248290e-01  -8.66025404e-01  -2.88675135e-01]
 [ -5.77350269e-01  -5.55111512e-17   8.16496581e-01]
 [ -7.07106781e-01   5.00000000e-01  -5.00000000e-01]]
